name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.device }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        echo "date=$(date '+%Y%m%d')" >> $GITHUB_ENV

    - name: Free disk space
      uses: sbwml/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Compile OpenWrt
      working-directory: /builder
      continue-on-error: true
      run: |
        curl -skL https://github.com/JohnsonRan/lede-m28k/raw/main/build.sh | bash

    - name: Extensive logs after a failed compilation
      working-directory: /builder
      run: |
        cd lede
        make V=s

    - name: Prepare Firmware Files
      working-directory: /builder
      run: |
        mkdir -p rom info
          cp -a lede/bin/targets/rockchip/armv8/*/*-sysupgrade.img.gz rom/
          cp -a lede/bin/targets/rockchip/armv8/*/*.manifest info/manifest.txt
          cp -a lede/bin/targets/rockchip/armv8/*/config.buildinfo info/config.buildinfo
          cp -a lede/bin/targets/rockchip/armv8/*/sha256sums info/sha256sums.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lede-m28k
        path: /builder/rom/*

    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ env.date }}
        allowUpdates: true
        tag: ${{ env.date }}
        commit: master
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "/builder/rom/*,/builder/info/*"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2