name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      ccache:
        description: 'Enable ccache (Use Cache to speed up next build)'
        type: boolean
        default: true

jobs:
  build:
    name: Build ${{ matrix.device }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup variables
      id: vars
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        echo date="$(date '+%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Free disk space
      uses: sbwml/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Fetch OpenWrt
      working-directory: /builder
      continue-on-error: true
      run: |
        CCACHE=${{ github.event.inputs.ccache }}
        curl -skL https://github.com/JohnsonRan/build_lede-m28k/raw/main/build.sh | bash

    - name: Restore Toolchain Cache
      if: ${{ github.event.inputs.ccache == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: |
         /builder/lede/build_dir
         /builder/lede/dl
         /builder/lede/staging_dir
         /builder/lede/tmp
        key: lede-m28k-toolchain
        
    - name: Restore Ccache
      if: ${{ github.event.inputs.ccache == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: /builder/lede/.ccache
        key: lede-m28k-ccache

    - name: Compile with GCC15
      working-directory: /builder
      run: |
        cd lede
        mkdir bin
        find ./staging_dir/ -name '*' -exec touch {} \; >/dev/null 2>&1
        find ./tmp/ -name '*' -exec touch {} \; >/dev/null 2>&1
        sed -i "/CONFIG_KERNEL_CC=/d" .config
        make defconfig > /dev/null
        make -j$(nproc) || make V=s

    - name: Delete Cached
      continue-on-error: true
      working-directory: /builder
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh cache delete lede-m28k-ccache || true
        gh cache delete lede-m28k-toolchain || true

    - name: Save Toolchain Cache
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: |
         /builder/lede/build_dir
         /builder/lede/dl
         /builder/lede/staging_dir
         /builder/lede/tmp
        key: lede-m28k-toolchain

    - name: Compile OpenWrt
      working-directory: /builder
      run: |
        cd lede
        echo "CONFIG_KERNEL_CC=\"ccache clang\"" >>.config
        make defconfig > /dev/null
        make -j$(nproc) || make V=s

    - name: Save Ccache
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: /builder/lede/.ccache
        key: lede-m28k-ccache

    - name: Prepare Firmware Files
      working-directory: /builder
      run: |
        mkdir -p rom info
          cp -a lede/bin/targets/rockchip/armv8/*-sysupgrade.img.gz rom/
          cp -a lede/bin/targets/rockchip/armv8/*.manifest info/manifest.txt
          cp -a lede/bin/targets/rockchip/armv8/config.buildinfo info/config.buildinfo
          cp -a lede/bin/targets/rockchip/armv8/sha256sums info/sha256sums.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lede-m28k
        path: /builder/rom/*

    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1.16.0
      with:
        name: ${{ steps.vars.outputs.date }}
        allowUpdates: true
        tag: ${{ steps.vars.outputs.date }}
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "/builder/rom/*,/builder/info/*"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2
